# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 256 # def: 256

# Directories
train_folder: /dl-mount/theano/subset/train_hkl_b256_b_256/
val_folder: /dl-mount/theano/subset/val_hkl_b256_b_256/
